### ISSUE TITLE
https://mjai.app/upload がうまく遷移していない

### ISSUE THREAD

**Issue by lv7777** [smly/mjai.app#19]
ファイルをアップロードしたあと200が帰ってきていますが、うまく遷移できておらず空白のページに飛んでいます

**Comment by smly** [comment]
試していただきありがとうございます。現在 mjai.app は機能を停止しており、今月末のサービス再開に向けて開発中です。
利用が可能との誤解を避けるために WebUI からのログインやドキュメントへのリンクを削除しました。

サービス再開後、後日確認いただきますようお願いします。
