### ISSUE TITLE
ドキュメントのexampleが壊れている

### ISSUE THREAD

**Issue by lv7777** [smly/mjai.app#20]
https://rowan-jewel-6dd.notion.site/Document-9c36de01d4d243e9a38c6b9e2a81da41
mjxのサンプルを投げたのですがgithubへのリンクが壊れていて、file not foundになっています
また、リンクにあるzipを投げてもcase 4で落ちるのですがこれは意図していますか？

**Comment by smly** [comment]
現在 mjai.app は機能を停止しており、今月末のサービス再開に向けて開発中です。
サービス再開後、後日確認いただきますようお願いします。

**Comment by lv7777** [comment]
ありがとうございます。最近麻雀AIやら麻雀関連の開発してるので期待してます
